RoboRecords/Controllers/GamesController.cs
/*
 * GamesController.cs: Games Web API Endpoints implementation 
 * Copyright (C) 2022, Refrag <Refragg>
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * See the 'LICENSE' file for more details.
 */

using System.Collections.Generic;
using System.Text.Json;
using Microsoft.AspNetCore.Mvc;
using RoboRecords.DbInteraction;
using RoboRecords.Models;

namespace RoboRecords.Controllers
{
    [Route("api/v1/[controller]")]
    [ApiController]
    public class GamesController : ControllerBase
    {
        [HttpGet]
        [Route("{id}")]
        public IActionResult GetGameFromId(int id)
        {
            if (!DbSelector.TryGetGameWithLevelsFromDbID(id, out RoboGame roboGame))
                return NotFound("No game found at that address");
            return Ok(roboGame);
        }

        [HttpGet]
        [Route("")]
        public IActionResult GetGames()
        {
            if (!DbSelector.TryGetGamesWithLevels(out List<RoboGame> roboGames))
                return Problem();
            return Ok(roboGames);
        }
    }
}

RoboRecords/Pages/AssetManager.cshtml.cs
/*
 * AssetManager.cshtml.cs: Backend of the Asset Manager website's page
 * Copyright (C) 2022, Refrag <Refragg>
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * See the 'LICENSE' file for more details.
 */

using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using RoboRecords.DbInteraction;
using RoboRecords.Models;

namespace RoboRecords.Pages;

public class AssetManager : RoboPageModel
{
    private Services.AssetManager _assetManager;
    
    public AssetManager(Services.AssetManager assetManager, IHttpContextAccessor httpContextAccessor) : base(httpContextAccessor)
    {
        _assetManager = assetManager;
    }
    
    public void OnGet()
    {
        
    }

    public IActionResult OnGetGames()
    {
        DbSelector.TryGetGames(out List<RoboGame> games);
        return new JsonResult(games);
    }
    
    public IActionResult OnGetCharacters()
    {
        DbSelector.TryGetCharacters(out List<RoboCharacter> characters);
        return new JsonResult(characters);
    }

    public IActionResult OnGetSiteAssets()
    {
        List<SiteAsset> siteAssets = _assetManager.GetSiteAssets();
        return siteAssets is not null ? new JsonResult(siteAssets) : NotFound();
    }
    
    public IActionResult OnGetGameAssets([FromQuery] int id)
    {
        DbSelector.TryGetGameFromDbID(id, out RoboGame game);
        
        return new JsonResult(_assetManager.GetGameAssets(game));
    }
    
    public IActionResult OnGetCharacterAssets([FromQuery] int id)
    {
        DbSelector.TryGetCharacterFromDbId(id, out RoboCharacter character);
        
        return new JsonResult(_assetManager.GetCharacterAssets(character));
    }
    
    public IActionResult OnPostTest([FromBody] SiteAsset asset)
    {
        Console.WriteLine(asset.DbId);
        Console.WriteLine(asset.Name);
        Console.WriteLine(asset.ImageInfo.IsValueCreated);
        Console.WriteLine(asset.ImageInfo.Value.Width);
        return Content("");
    }
}

RoboRecords/Pages/EditGame.cshtml.cs
/*
 * EditGame.cshtml.cs: Backend for the game edition page
 * Copyright (C) 2022, Ors <Riku-S>, Zenya <Zeritar> and Refrag <Refragg>
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * See the 'LICENSE' file for more details.
 */

using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Mime;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using System.Web;
using Microsoft.AspNetCore.Antiforgery;
using RoboRecords.DatabaseContexts;
using RoboRecords.DbInteraction;
using RoboRecords.Models;

namespace RoboRecords.Pages
{
    public class EditGame : RoboPageModel
    {
        [BindProperty]
        public GameEditDb GameEdit { get; set; }
        public static RoboGame Game;
        public string Token;
        public EditGame(IHttpContextAccessor httpContextAccessor) : base(httpContextAccessor)
        {
        }
        
        public void OnGet()
        {
            DbSelector.TryGetGamesWithLevels(out var roboGames);

            var id = HttpUtility.ParseQueryString(Request.QueryString.ToString()).Get("id");

            if (id != null)
            {
                DbSelector.TryGetGameWithRecordsFromID(id, out Game);
            }
            else
            {
                // SRB2 2.2 default for testing. Should be changed to throw an error.
                DbSelector.TryGetGameWithRecordsFromID("sonicroboblast2v22", out Game);
            }
        }

        class InterpretedLevel
        {
            public string LevelName{ get; set; }
            public string Act{ get; set; }
            public string LevelNumber{ get; set; }
            public bool Nights{ get; set; }
            public string IconUrl{ get; set; }
        }
        class InterpretedGroup
        {
            public string Name{ get; set; }
            public bool WriteLevelNames{ get; set; }
            public List<InterpretedLevel> Levels{ get; set; }
        }
        public class GameData
        {
            public string Name { get; set; }
            public string UrlName { get; set; }
            public string IconPath { get; set; }
            public string GroupsJson { get; set; }
        }
        
        public IActionResult OnPostSaveAsync([FromBody] GameData data)
        {
            // TODO: Compare the data to existing data, and replace what needs to be replaced in order to edit the game
            
            try
            {
                RoboGame game = new RoboGame(data.Name);
                game.Name = data.Name;
                game.UrlName = data.UrlName;
                game.IconPath = data.IconPath;

                List<InterpretedGroup> jsonGroups = System.Text.Json.JsonSerializer.Deserialize<List<InterpretedGroup>>(data.GroupsJson);
                
                Logger.Log(game.Name + ", " + game.UrlName);
                List<LevelGroup> groups = new List<LevelGroup>();
                foreach (InterpretedGroup levelGroup in jsonGroups)
                {
                    LevelGroup newGroup = new LevelGroup();
                    newGroup.Name = levelGroup.Name;
                    newGroup.WriteLevelNames = levelGroup.WriteLevelNames;
                    Logger.Log("Write names: " + levelGroup.WriteLevelNames + ", Name: " + levelGroup.Name + ", " + levelGroup.Levels.Count);
                    newGroup.Levels = new List<RoboLevel>();
                    foreach (InterpretedLevel level in levelGroup.Levels)
                    {
                        Logger.Log("Url: " + level.IconUrl + ", Act: " + level.Act + ", Nights: " + level.Nights + ", Name: " + level.LevelName);
                        RoboLevel gameLevel = Game.GetLevelByNumber(Int32.Parse(level.LevelNumber) );
                        RoboLevel newLevel = new RoboLevel(Int32.Parse(level.LevelNumber), level.LevelName, Int32.Parse(level.Act), level.Nights);
                        
                        newLevel.IconUrl = level.IconUrl;
                        newLevel.LevelGroup = newGroup;
                        
                        if (gameLevel is not null)
                        {
                            //newLevel.Records = gameLevel.Records;
                            IList<RoboRecord> records = new List<RoboRecord>();
                            foreach (RoboRecord record in gameLevel.Records)
                            {
                                record.Level = newLevel;
                                records.Add(record);
                            }
                            newLevel.Records = records;
                        }
                        
                        newGroup.Levels.Add(newLevel);
                    }

                    newGroup.RoboGame = game;
                    groups.Add(newGroup);
                }
                game.LevelGroups.Clear();
                game.LevelGroups = groups;
                using (RoboRecordsDbContext context = new RoboRecordsDbContext())
                {
                    /*
                    foreach (LevelGroup group in Game.LevelGroups)
                    {
                        foreach (RoboLevel level in group.Levels)
                        {
                            if (level.Records is not null)
                            {
                                foreach (RoboRecord record in level.Records)
                                {
                                    Logger.Log("Removing record...");
                                    context.RoboRecords.Remove(record);
                                }
                                context.Update(level);
                            }
                            Logger.Log("Removing level...");
                            context.RoboLevels.Remove(level);
                            context.Update(group);
                        }
                        Logger.Log("Removing group...");
                        context.LevelGroups.Remove(group);
                        context.Update(Game);
                    }*/
                    Logger.Log("Removing game...");
                    context.RoboGames.Remove(Game);

                    Logger.Log("Updating game...");
                    context.RoboGames.Add(game);

                    Logger.Log("Saving...");
                    context.SaveChangesAsync().Wait();
                }
            }
            catch (Exception e)
            {
                Logger.Log("Error while trying to save a game: " + e.Message, Logger.LogLevel.Error);
                throw;
            }
            
            return Page();
        }
    }
}

RoboRecords/Pages/Submit.cshtml.cs
/*
 * Submit.cshtml.cs: Backend for the replay submission page
 * Copyright (C) 2022, Ors <Riku-S>, Zenya <Zeritar> and Refrag <Refragg>
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * See the 'LICENSE' file for more details.
 */

using Microsoft.AspNetCore.Html;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using RoboRecords.DatabaseContexts;
using RoboRecords.DbInteraction;
using RoboRecords.Models;

namespace RoboRecords.Pages
{
    public class Submit : RoboPageModel
    {
        public static List<RoboRecord> RecordList;
        [BindProperty]
        public ReplayUploadDb FileUpload { get; set; }
        public static RoboGame Game;
        public static bool UserLoggedIn;

        public Submit(IHttpContextAccessor httpContextAccessor) : base(httpContextAccessor)
        {
        }

        public class ErrorMessage
        {
            public string ReplayName;
            public string Message;

            public ErrorMessage(string replayName, string message)
            {
                ReplayName = replayName;
                Message = message;
            }
        }

        public static List<ErrorMessage> ErrorMessages;
        public void OnGet()
        {
            RecordList = new List<RoboRecord>();
            ErrorMessages = new List<ErrorMessage>();
            // TODO: Change to only select current level, as this won't make Entity Framework
            // generate an UPDATE for the whole RoboGame object.
            // Not gonna start changing stuff here, as it might break the Submit page.
            // Same method as in Map page can be used to get just the level.
            // DbInserter.AddRecord just
            DbSelector.TryGetGamesWithLevels(out var roboGames);

            var gameId = HttpUtility.ParseQueryString(Request.QueryString.ToString()).Get("game");
            if (gameId != null)
            {
                Game = roboGames.Find(game => game.UrlName == gameId);
            }
            else
            {
                // SRB2 2.2 default for testing. Should be changed to throw an error.
                Game = roboGames.Find(game => game.UrlName == "sonicroboblast2v22");
            }

            UserLoggedIn = IsLoggedIn;
        }

        public IActionResult OnPostAsync(ReplayUploadDb fileUpload)
        {
            if (fileUpload == null || fileUpload.FormFiles == null || fileUpload.FormFiles.Count == 0)
            {
                // TODO: Error message thing or something
                return null;
            }

            ErrorMessages.Clear();
            List<IFormFile> files = fileUpload.FormFiles;
            long size = files.Sum(f => f.Length);

            foreach (var formFile in files)
            {
                if (formFile.Length > 0)
                {
                    var stream = formFile.OpenReadStream();
                    var bytes = new byte[formFile.Length];
                    stream.Read(bytes, 0, (int)formFile.Length);
                    var rec = new RoboRecord(CurrentUser, bytes.ToArray());

                    // If something went wrong while reading the replay, don't upload it.
                    switch (rec.readStatus)
                    {
                        case RoboRecord.ReadStatus.Success:
                            // The condition SHOULD always be true, but let's be careful
                            if (rec.FileBytes != null && rec.FileBytes.Length > 0)
                            {
                                RecordList.Add(rec);
                            }
                            else
                            {
                                ErrorMessages.Add(new ErrorMessage(formFile.FileName, RoboRecord.MessageErrorUnknown));
                            }
                            break;
                        case RoboRecord.ReadStatus.ErrorInvalid:
                            ErrorMessages.Add(new ErrorMessage(formFile.FileName, RoboRecord.MessageErrorInvalid));
                            break;
                        case RoboRecord.ReadStatus.ErrorReading:
                            ErrorMessages.Add(new ErrorMessage(formFile.FileName, RoboRecord.MessageErrorReading));
                            break;
                        case RoboRecord.ReadStatus.ErrorUnfinished:
                            ErrorMessages.Add(new ErrorMessage(formFile.FileName, RoboRecord.MessageErrorIncomplete));
                            break;
                        case RoboRecord.ReadStatus.ErrorNotSrb2:
                            ErrorMessages.Add(new ErrorMessage(formFile.FileName, RoboRecord.MessageErrorNotSrb2));
                            break;
                        default:
                            ErrorMessages.Add(new ErrorMessage(formFile.FileName, RoboRecord.MessageErrorUnknown));
                            break;
                    }
                }
            }
            // Process uploaded files
            // Don't rely on or trust the FileName property without validation.

            // return new OkObjectResult(new {count = files.Count, size});
            return null;
        }

        public IActionResult OnPostUploadAsync()
        {
            ErrorMessages.Clear();
            if (!IsLoggedIn)
                return null;

            foreach (var record in RecordList)
            {
                // TODO: Make this less horribly inefficient by only reading the file here
                // Check if this is the best time or worth uploading
                DbSelector.TryGetGameLevelFromMapId(Game.UrlName, record.LevelNumber.ToString(), out RoboLevel level);
                DbInserter.AddRecordIfNeeded(record, level);
            }
            
            return RedirectToPage();
        }
        
        public IActionResult OnPostCancelAsync()
        {
            ErrorMessages.Clear();
            // Refresh the page to cancel the uploads
            return RedirectToPage();
        }

        public IActionResult OnPostDeleteAsync(int rec)
        {
            ErrorMessages.Clear();
            // Should NEVER happen
            if (RecordList.Count <= rec)
            {
                return null;
            }

            RecordList.RemoveAt(rec);
            return null;
        }
    }
}

RoboRecords/Pages/GamePage.cshtml
@page
@using RoboRecords.Models
@model RoboRecords.Pages.GamePage

@{
    ViewData["Title"] = @GamePage.CurrentGame.Name;
}

<!DOCTYPE html>

<!--
 GamePage.cshtml: Frontend for a single game page
 Copyright (C) 2022, Lemin <Leminn>, Refrag <Refragg> and Ors <Riku-S>
 
 This program is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.
 See the 'LICENSE' file for more details.
-->

<html lang="en">
<div class="text-center">
    <h1 class="title-font">@GamePage.CurrentGame.Name</h1>
    <h2 class="lead">Click a level to see all of its records!</h2>
    <input type="button" onclick="location.href='@String.Format("/Submit?game={0}", GamePage.CurrentGame.UrlName)';" value="Submit a replay" />
</div>
<body class="">

<div class="game-list" style="position: center; text-align: center;">
    @foreach (var levelGroup in GamePage.CurrentGame.LevelGroups)
    {
        <br>
        <span class="title-font" style="font-size: 20px">@levelGroup.Name </span>
        <br>
        foreach (var level in levelGroup.Levels)
        {
            <div class="levelBox" style="background-image: url(@level.IconUrl); image-rendering: pixelated; max-width: unset">
                <a href=@String.Format("/Map?game={0}&map={1}", GamePage.CurrentGame.UrlName, level.LevelNumber) style="color: white; text-decoration: none;">
                    <div style="width: 100%; height: 100%; position: relative">
                        <div style="text-align: right;">
                            @if (levelGroup.WriteLevelNames)
                            {
                                @level.LevelName
                                <br>
                            }
                            @if (level.Act > 0)
                            {
                                <span class="title-font" style="font-size: 20px">act</span>
                                <span class="title-font-number" style="font-size: 32px"> @level.Act </span>
                            }
                        </div>
                        <span style="position:absolute; bottom: 4px; left: 4px; text-align: left; line-height: 120%">
                            @if (!level.Nights)
                            {
                                @foreach (var character in CharacterManager.StandardCharacters)
                                {
                                    var record = level.GetBestRecord(character);
                                    if (record is not null)
                                    {
                                        <img src=@character.IconUrl alt=@character.Name width="24px">
                                        <span class="number-display" style="font-size: x-large"> @RoboRecord.GetTimeFromTics(record.Tics) </span><span> @record.Uploader.UserNameNoDiscrim</span><br>
                                    }
                                }
                            }
                            else
                            {
                                var timeRecord = level.GetBestTimeRecord();
                                var scoreRecord = level.GetBestScoreRecord();
                                if (timeRecord is not null)
                                {
                                    <img src=@timeRecord.Character.IconUrl alt=@timeRecord.Character.Name width="24px">
                                    <span class="number-display" style="font-size: x-large"> @RoboRecord.GetTimeFromTics(timeRecord.Tics) </span><span> @timeRecord.Uploader.UserNameNoDiscrim</span><br>
                                }
                                if (scoreRecord is not null)
                                {
                                    <img src=@scoreRecord.Character.IconUrl alt=@scoreRecord.Character.Name width="24px">
                                    <span class="number-display" style="font-size: x-large"> @scoreRecord.Score </span><span> @scoreRecord.Uploader.UserNameNoDiscrim</span><br>
                                }
                            }
                        </span>
                    </div>
                </a>
            </div>
        }
        <br/>
    }
</div>
<br/>
<br/>

</body>
</html>

<style>
    nav {
    background: linear-gradient(180deg, rgba(2,0,36,1) 0%, rgba(0,15,149,1) 100%);
    }
    footer {
     
    }
    body {
      background: linear-gradient( rgba(0, 0, 0, 0.50), rgba(0, 0, 0, 75) ), url(@GamePage.CurrentGame.IconPath) center;
      background-size: cover;
  background-repeat: no-repeat;
  background-attachment: fixed;
    }

</style>

RoboRecords/Pages/Games.cshtml
@page
@model RoboRecords.Pages.Games

<!--
 Games.cshtml: Frontend for the games website's page
 Copyright (C) 2022, Lemin <Leminn>, Refrag <Refragg> and Ors <Riku-S>
 
 This program is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.
 See the 'LICENSE' file for more details.
-->

@{
    ViewData["Title"] = "Games";
}
<div class="text-center">
    <h1 class="">Games/Levelpacks</h1>
    <h2 class="lead">Choose a game to view and submit records.</h2>
</div>
<div style="text-align: center">
    @foreach (var game in Games.RoboGames)
    {
        <div class="gameBox box-shadow" style="background-image: url(@game.IconPath); background-position: center;">
            <a href=@game.GetAspLink() style="color: white; text-underline-offset: 10px">
                <div style="width: 100%; height: 100%">
                <span class="gameText title-font">@game.Name</span>
                    
                </div>
            </a>
        </div>
    }
</div>

<style>
    body {
      background: linear-gradient( rgba(0, 0, 0, 0.75), rgba(0, 0, 0, 0.75) ), url('@FileManager.AssetsDirectoryName/images/dreamhill1.png');
                  background-size: 100%;
                  background-repeat: no-repeat;
                  margin: 0;
    }
</style>

RoboRecords/Pages/Submit.cshtml
@page
@using RoboRecords.Models
@using Microsoft.AspNetCore.Http
@model RoboRecords.Pages.Submit

<!--
 Submit.cshtml: Frontend for the replay submission page
 Copyright (C) 2022, Ors <Riku-S> and Refrag <Refragg>
 
 This program is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.
 See the 'LICENSE' file for more details.
-->

@{
    ViewData["Title"] = "Submit";
}

<html>
<head>
    <title>Submit</title>
</head>
<body>
@if (Submit.UserLoggedIn)
{
    <div>
        Please submit a replay.<br>
        Game: @Submit.Game.Name
    </div>
}
else
{
    <div>
        Please log in to submit a replay.<br>
        <input type="button" onclick="location.href='/Login'" value="Log in"/>
    </div>
}

<div class="modal fade" id="errorModal" tabindex="-1" role="dialog" aria-labelledby="errorModalTitleText" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header" style="background-color: #d13532">
                <h5 class="modal-title" id="errorModalTitleText" >Errors were found in replays:</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div id="errorModalBodyText" class="modal-body" style="background-color: #303030">
                @foreach (Submit.ErrorMessage message in Submit.ErrorMessages)
                {
                    <p>@message.ReplayName: @message.Message</p>
                }
            </div>
            <div class="modal-footer" style="background-color: #303030">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

@if (Submit.UserLoggedIn)
{
    <div class="container">
        <form enctype="multipart/form-data" method="post">
            <dl>
                <dt>
                    <label asp-for="FileUpload.FormFiles"></label>
                </dt>
                <dd>
                    <input asp-for="FileUpload.FormFiles" type="file" multiple/>
                    <span asp-validation-for="FileUpload"></span>
                </dd>
            </dl>
            <input asp-page-handler="Post" type="submit" value="Submit"/>

        </form>
        Submissions:
        @if (Submit.RecordList.Count > 0)
        {
            RoboGame roboGame = Submit.Game;
            bool hasNights = Submit.RecordList.Find(record => roboGame.GetLevelByNumber(record.LevelNumber) is not null && roboGame.GetLevelByNumber(record.LevelNumber).Nights) is not null;
            <div>
                <table>
                    <tr class="title-font" style="text-align: center">
                        <th style="font-weight: unset">

                        </th>
                        <th style="font-weight: unset">
                            Level
                        </th>
                        <th style="font-weight: unset">
                            Time
                        </th>
                        @if (hasNights)
                        {
                            <th style="font-weight: unset">
                                Score
                            </th>
                        }
                        <th style="font-weight: unset">
                            Version
                        </th>
                        <th style="font-weight: unset">

                        </th>
                    </tr>

                    @for (var recordCount = 0; recordCount < Submit.RecordList.Count; recordCount++)
                    {
                        var record = Submit.RecordList[recordCount];
                        var level = roboGame.GetLevelByNumber(record.LevelNumber);
                        if (level is not null)
                        {
                            var levelString = level.LevelName + (level.Act > 0 ?  " " + level.Act : "");
                            <tr class="title-font" style="text-align: center">
                                <th style="font-weight: unset">
                                    @if (record.Character is not null)
                                    {
                                        <img src=@record.Character.IconUrl alt=@record.Character.Name width="32px">
                                    }
                                </th>
                                <th style="font-weight: unset">
                                    @levelString
                                </th>
                                <th style="font-weight: unset">
                                    <span class="number-display" style="font-size: x-large"> @RoboRecord.GetTimeFromTics(record.Tics) </span>
                                </th>
                                @if (hasNights)
                                {
                                    <th style="font-weight: unset">
                                        <span class="number-display" style="font-size: x-large"> @record.Score </span>
                                    </th>
                                }
                                <th style="font-weight: unset">
                                    @record.VersionString
                                </th>
                                <th style="font-weight: unset">
                                    <form asp-page-handler="delete" method="post">
                                        <button>X</button>
                                        <input type="hidden" name="rec" value="@recordCount"/>
                                    </form>
                                </th>
                            </tr>
                        }
                    }
                    <tr>
                        <td colspan="5" style="alignment: right">
                            <form enctype="multipart/form-data" method="post">
                                <input asp-page-handler="Cancel" type="submit" value="Cancel"/>
                                <input asp-page-handler="Upload" type="submit" value="Upload to leaderboards"/>
                            </form>
                        </td>
                    </tr>

                </table>

            </div>

        }
        else
        {
            <p>
                No submission yet. Please submit a replay.
            </p>
        }
    </div>
}

@if (Submit.ErrorMessages.Count > 0)
{
    <script type="text/javascript">
    function showError()
    {
        console.log("Calling modal");
        $('#errorModal').modal()
        console.log("Modal called");
    }
    
    window.onload = function() {
        showError();
    };
    </script>
}



</body>
<style>
    body {
      background: linear-gradient( rgba(0, 0, 0, 0.50), rgba(0, 0, 0, 75) ), url(@Submit.Game.IconPath) center;
      background-size: cover;
      background-repeat: no-repeat;
      background-attachment: fixed;
    }
    
    
     screen and (max-width: 800px) {
      h1 {
             font-size: 6vw !important;
         }
         
         h3 {
             font-size: 4vw;
         }
    
     }
   
        tr:nth-child(even)
        {
            background: rgba(32, 32, 32, 0.50);
        }
        tr:nth-child(odd)
        {
            background: rgba(64, 64, 64, 0.50);
        }
        tr:first-child th:first-child
        {
            border-radius: 0.6em 0 0 0;
        }
        tr:first-child th:last-child
        {
            border-radius: 0 0.6em 0 0;
        }
        tr:first-child
        {
            background-color: #404040;
        }
        tr:last-child td:first-child
        {
            background: rgba(32, 32, 32, 0.50);
            border-radius: 0 0 0.6em 0.6em;
            padding: 15px;
        }
        td, th
        {
        padding-left: 15px;
        padding-right: 15px;
        }
</style>
</html>